### ISSUE TITLE
`laminas/laminas-cache` is specified in both `require` AND `require-dev` sections of `composer.json`

### ISSUE THREAD

**Issue by internalsystemerror** [laminas/laminas-cache-storage-adapter-apcu#42]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.1.0

#### Summary

Reviewing these cache packages, I noticed the titular problem which I was previously told explicitly to NOT do:
- https://github.com/composer/composer/issues/3742#issuecomment-74540885.

#### Current behavior

`composer install --no-dev` installs `laminas/cache` `3.0.x-dev` and not `3.0`. Whereas this may suffice for the use case here as neither the lock file nor `require-dev` section SHOULD be read during installation as a library, this isn't guaranteed as noted om the above issue.

#### How to reproduce

Check out repository locally and run `composer install --no-dev`.

#### Expected behavior

A package should appear only in `require` OR `require-dev` and not both.

**Comment by boesing** [comment]
This is still a thing due to the fact that I had to provide some kind of pre-release compatibility.
Meanwhile, we can just drop it.
Will do that with PHP 8.2 support PR in the next couple of minutes.
